#!/bin/bash

#        The MIT License (MIT)
#        Copyright 2013 sunus Lee, sunuslee [ A-t ] gmail [ d0t ] com
#
#        Permission is hereby granted, free of charge, to any person obtaining
#        a copy of this software and associated documentation files (the
#        "Software"), to deal in the Software without restriction, including
#        without limitation the rights to use, copy, modify, merge, publish,
#        distribute, sublicense, and/or sell copies of the Software, and to
#        permit persons to whom the Software is furnished to do so, subject to
#        the following conditions:
#
#        The above copyright notice and this permission notice shall be
#        included in all copies or substantial portions of the Software.
#
#        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#        NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#        LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#        OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#        WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#DEBUG:
#set -x

CLOUD_DRIVER_ROOT="/Users/sunus/Dropbox/MacBook"

function help() {
    echo  "Usage: bub option path1 path2 ..."
    echo  "options:"
    echo  "-s Use to selete custome file/directories. do not copy the full path and parent directory"
    echo  "-i Normal Dropbox mode, just copy to Dropbox directory. same as cp"
    echo  "-h Show this help and exit"
}

function get_abspath() {
    if [[ $1 = /* ]]; then
        echo "$1"
    else
        echo "$(pwd)/$1"
    fi
}

# take only ABSOLUTE PATH as $1
# return absolute path for $1
# this function is not validating $1 at all!

function backup() {
    dir="$(dirname "$1")"
    dst="$CLOUD_DRIVER_ROOT/$dir"
    mkdir -p "$dst"
    cp -vrf "$1" "$dst"
    if [ $? -eq 0 ]; then
        echo "Back up file $file OK"
    else
        echo "Back up file $file Fail"
    fi
}

function main() {
    if [ ! -d "$CLOUD_DRIVER_ROOT" ]; then
        mkdir -p "$CLOUD_DRIVER_ROOT"
    fi
    if [ "$1" == "-h" ]; then
        help
        exit 0
    elif [ "$1" == "-i" ]; then
        shift
        cp "$@"
    elif [ "$1" == "-s" ]; then
        shift
        for target in "$@"; do
            target="$(get_abspath "$target")"
            echo "Processing target: "$target""
            if [ -d "$target" ]; then
                backup "$target"
            elif [ -f "$target" ]; then
                backup "$target"
            else
                echo "Unsupport file $target"
            fi
        done
    else
        echo "unknown option"
        help
    fi
}

main "$@"
